server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示是否将自己注册进eurekaserve 默认为true
    register-with-eureka: false
    #是否从eurekaserve抓取已有的注册信息。默认为true 单节点无所谓 。集群必须设置为true 才能配合ribben使用
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
